# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f3e9d51c405e3438bdde1e5d7ab36100db497f528951ed44d6d86fe1f6086cd8e5da65cd613a0de71c99c06401db391ba2153500c3907d67426c123b08e805

test:
  secret_key_base: c57b81baf74a72cd57e53db7890407b2341662908f004c2ce8538ce17cfb61c4924349990cc770b1b941e97a841bbe69c99ef75c93e64be6878768fc8f52a2ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
